### ISSUE TITLE
Change sample app

### ISSUE THREAD

**Issue by dukhanov** [dukhanov/Cordova-Flic#2]
Change sample app regarding the latest changes in the plugin API

**Comment by dukhanov** [comment]
Fixed since the latest release version 1.0.1
https://github.com/dukhanov/Cordova-Flic/commit/cc31d94957986894a457719d672ed245d3f703e3

**Comment by jguix** [comment]
Hi, someone told me about this update, a very promising one. Would you mind to push changes to my project?

**Comment by dukhanov** [comment]
Hi, I've made a lot of changes, it will be very difficult to merge it.

**Comment by jguix** [comment]
Ok, I'll take care of it.

2016-09-22 14:39 GMT+02:00 Maxim notifications@github.com:
