### ISSUE TITLE
Cannot build iOS project including Cordova-Flic

### ISSUE THREAD

**Issue by b2rosado** [dukhanov/Cordova-Flic#3]
Hi.
When trying to build a iOS Cordova project using this plugin, it fails with the following message:
```
"_OBJC_CLASS_$_CLLocationManager", referenced from:
objc-class-ref in Flic.o
ld: symbol(s) not found for architecture armv7
```
Any idea why this may be happening or how to fix it?
Tried many possible fixes that occurred in similar cases, without any progress.

**Comment by dukhanov** [comment]
Hi.
I've checked, I see the problem. 
I will fix it soon.

UPD:
I've faced with the same problem when I'm trying to build for the simulator.
I case I build with --device param the issue is not reproduced.
Unfortunately, this version of the plugin has not supported simulators yet.

**Comment by b2rosado** [comment]
I am not building for the simulator.
Actually, I'm trying to deploy directly for an iPad mini.

**Comment by dukhanov** [comment]
Have you installed node-xcode locally?
`node i xcode`
If not, please remove the plugin first, 
then run command in the project folder `node i xcode`
then try to run the project `cordova run ios`

**Comment by qpwr** [comment]
The same is happening for me when trying to "cordova build ios". Any news about this issue? I *have* installed npm xcode before I installed the plugin. This is the error:
```
Undefined symbols for architecture i386:
  "_OBJC_CLASS_$_SCLFlicManager", referenced from:
      objc-class-ref in Flic.o
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by mrcbnsls** [comment]
@dukhanov, are there any plans to continue developing this project?

**Comment by dukhanov** [comment]
@mrcbnsls Yes, ended. 
The issue described above does not reproduce with default Cordova application. It might be some kind of project specific issue.
